/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dados.Cliente;
import javax.swing.JOptionPane;
import repositorio.RepositorioCliente;

/**
 *
 * @author fabio
 */
public class TelaCliente extends javax.swing.JFrame {

    //Alocado Memoria Para Objeto
    RepositorioCliente repositorioCliente;
    TelaEditarCliente chamaTelaEditC;

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        repositorioCliente = new RepositorioCliente();
        //Seta A Tabela Personalizada Para Jtable
        jTable1.setModel(repositorioCliente);
        //Inicializa Clientes Testes
        repositorioCliente.inicializaCliente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPesquisaC = new javax.swing.JTextField();
        jBPesquisaC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTNomeC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCpfC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTEmailC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTTelC = new javax.swing.JTextField();
        jBAddC = new javax.swing.JButton();
        jBRemoveC = new javax.swing.JButton();
        jBEditaC = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cliente");
        setResizable(false);

        jLabel1.setText("Nome: ");

        jBPesquisaC.setText("Pesquisar !");
        jBPesquisaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaCActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nome: ");

        jLabel3.setText("Cpf:");

        jLabel4.setText("Email: ");

        jLabel5.setText("Telefone: ");

        jBAddC.setText("Adicionar !");
        jBAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddCActionPerformed(evt);
            }
        });

        jBRemoveC.setText("Remover !");
        jBRemoveC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoveCActionPerformed(evt);
            }
        });

        jBEditaC.setText("Editar !");
        jBEditaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditaCActionPerformed(evt);
            }
        });

        jButton4.setText("Sair !");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(108, 108, 108)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(66, 66, 66))
                                    .addComponent(jTTelC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 67, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAddC)
                                .addGap(52, 52, 52)
                                .addComponent(jBRemoveC)
                                .addGap(59, 59, 59)
                                .addComponent(jBEditaC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPesquisaC, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBPesquisaC)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPesquisaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisaC))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAddC)
                    .addComponent(jBRemoveC)
                    .addComponent(jBEditaC)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Botão Para Fechar A Tela

        int opcao = JOptionPane.showConfirmDialog(this, "Você Quer Voltar Para Tela Principal ?", null, JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            //Limpando Todos Os Campos
            jTPesquisaC.setText("");
            jTNomeC.setText("");
            jTCpfC.setText("");
            jTEmailC.setText("");
            jTTelC.setText("");

            //desselecinando Qualquer Linha
            jTable1.clearSelection();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddCActionPerformed
        // Botão Para Adicionar
        if (jTNomeC.getText().length() > 0 && jTCpfC.getText().length() > 0 && jTEmailC.getText().length() > 0 && jTTelC.getText().length() > 0) {
            //Pegando Os Campos
            String nome = jTNomeC.getText();
            String cpf = jTCpfC.getText();
            String email = jTEmailC.getText();
            String telefone = jTTelC.getText();

            //Adiciona Cliente Para ArrayList
            Cliente c = new Cliente(nome, cpf, email, telefone);
            repositorioCliente.addCliente(c);

            //Limpando Os Campos
            jTNomeC.setText("");
            jTCpfC.setText("");
            jTEmailC.setText("");
            jTTelC.setText("");

            JOptionPane.showMessageDialog(this, "Cliente Adicionado Com Sucesso" + "\n" + c);

        } else {
            JOptionPane.showMessageDialog(this, "Campo(s) Em Branco");
        }


    }//GEN-LAST:event_jBAddCActionPerformed

    private void jBRemoveCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoveCActionPerformed
        // Botão Para Remover
        if (jTable1.getRowCount() != 0) {

            //Verifica Se Tem Linha Selecionada
            if (jTable1.getSelectedRow() != -1) {
                Cliente clienteSelecionado = repositorioCliente.getCliente(jTable1.getSelectedRow());

                int opcao = JOptionPane.showConfirmDialog(this, clienteSelecionado, "Quer Apagar O Cliente ?", JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.YES_OPTION) {
                    repositorioCliente.RemoveCliente(jTable1.getSelectedRow());
                    JOptionPane.showMessageDialog(this, "Cliente Removido Com Sucesso");

                } else {
                    JOptionPane.showMessageDialog(this, "Remoção Abortada");
                    jTable1.clearSelection();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Nenhum Cliente Selecionado");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não Possui Clientes Cadastrados No Sistema");
        }

    }//GEN-LAST:event_jBRemoveCActionPerformed

    private void jBEditaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditaCActionPerformed
        // Botão Para Editar
        if (jTable1.getRowCount() != 0) {

            //Verifica Se Tem Linha Selecionada
            if (jTable1.getSelectedRow() != -1) {

                Cliente clienteSelecionado = repositorioCliente.getCliente(jTable1.getSelectedRow());

                int opcao = JOptionPane.showConfirmDialog(this, clienteSelecionado, "Quer Apagar O Cliente ?", JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.YES_OPTION) {
                    if (chamaTelaEditC == null){
                       chamaTelaEditC = new TelaEditarCliente(clienteSelecionado); 
                    }
                    chamaTelaEditC.setVisible(true);
                    repositorioCliente.AtualizaTableC();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Edição Abortada");
                    jTable1.clearSelection();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Nenhum Cliente Selecionado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não Possui Cliente Cadastrado No Sistema");
        }
    }//GEN-LAST:event_jBEditaCActionPerformed

    private void jBPesquisaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaCActionPerformed
        // Botão Para Pesquisar
        if (jTPesquisaC.getText().length() > 0) {
            Cliente c = repositorioCliente.pesquisaCliente(jTPesquisaC.getText());

            if (c != null) {
                JOptionPane.showMessageDialog(this, "Cliente Encontrado" + "\n" + c);
                //Limpando Campo
                jTPesquisaC.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Não Tem Cliente Com Esse Nome Cadastrado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Campo Em Branco");
        }

    }//GEN-LAST:event_jBPesquisaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddC;
    private javax.swing.JButton jBEditaC;
    private javax.swing.JButton jBPesquisaC;
    private javax.swing.JButton jBRemoveC;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCpfC;
    private javax.swing.JTextField jTEmailC;
    private javax.swing.JTextField jTNomeC;
    private javax.swing.JTextField jTPesquisaC;
    private javax.swing.JTextField jTTelC;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
