/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dados.Produto;
import javax.swing.JOptionPane;
import repositorio.RepositorioProduto;

/**
 *
 * @author fabio
 */
public class TelaProduto extends javax.swing.JFrame {
    //Instanciando As Classes
    RepositorioProduto repositorioProduto;
    TelaEditarProduto chamaTelaProduto;

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        //Aloca Memória Para Objeto
        repositorioProduto = new RepositorioProduto();
        //Seta o Modelo AbastractModel
        jTableP.setModel(repositorioProduto);

        //Inicializa Produtos Para Teste
        repositorioProduto.inicializaProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPesquisaP = new javax.swing.JTextField();
        jBPesquisaP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableP = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTNomeP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTDescP = new javax.swing.JTextField();
        jTPrecoVP = new javax.swing.JTextField();
        jTPrecoCP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBAddP = new javax.swing.JButton();
        jBRemoveP = new javax.swing.JButton();
        jBEditaP = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Produto");
        setResizable(false);

        jLabel1.setText("Código: ");

        jBPesquisaP.setText("Pesquisar !");
        jBPesquisaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaPActionPerformed(evt);
            }
        });

        jTableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableP);

        jLabel2.setText("Nome: ");

        jLabel3.setText("Descrição: ");

        jLabel4.setText("Preço De Venda:");

        jLabel5.setText("Preço De Custo:");

        jBAddP.setText("Adicionar !");
        jBAddP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddPActionPerformed(evt);
            }
        });

        jBRemoveP.setText("Remover !");
        jBRemoveP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemovePActionPerformed(evt);
            }
        });

        jBEditaP.setText("Editar!");
        jBEditaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditaPActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAddP)
                        .addGap(39, 39, 39)
                        .addComponent(jBRemoveP)
                        .addGap(52, 52, 52)
                        .addComponent(jBEditaP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTDescP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jTPrecoVP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton2))
                    .addComponent(jLabel5)
                    .addComponent(jTPrecoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPesquisaP, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBPesquisaP)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPesquisaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisaP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDescP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPrecoVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPrecoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAddP)
                    .addComponent(jBRemoveP)
                    .addComponent(jBEditaP)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Fecha A Tela Produto

        int opcao = JOptionPane.showConfirmDialog(this, "Você Quer Voltar Para Tela Principal ?", null, JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            //Limpando Os Campos Após Fechar
            jTPesquisaP.setText("");
            jTNomeP.setText("");
            jTDescP.setText("");
            jTPrecoVP.setText("");
            jTPrecoCP.setText("");

            //Desselecionando Qualquer Linha Selecionada
            jTableP.clearSelection();

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBAddPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddPActionPerformed
        // Botão Para Adicionar Produto
        if (jTNomeP.getText().length() > 0 && jTDescP.getText().length() > 0 && jTPrecoVP.getText().length() > 0 && jTPrecoCP.getText().length() > 0) {

            //Pegando os Campos De Texto
            String nome = jTNomeP.getText();
            String desc = jTDescP.getText();
            double pv = Double.parseDouble(jTPrecoVP.getText());
            double pc = Double.parseDouble(jTPrecoCP.getText());

            //Adicionado No ArrayList   
            Produto p = new Produto(nome, desc, pv, pc);
            repositorioProduto.AddProduto(p);

            //Limpando Os Campos
            jTNomeP.setText("");
            jTDescP.setText("");
            jTPrecoVP.setText("");
            jTPrecoCP.setText("");

            JOptionPane.showMessageDialog(this, "Produto Adicionado Com Sucesso"
                    + "\n" + p);

        } else {
            JOptionPane.showMessageDialog(this, "Campo(s) Em Branco");
        }
    }//GEN-LAST:event_jBAddPActionPerformed

    private void jBRemovePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemovePActionPerformed
        // Botão Para Remover
        if (jTableP.getRowCount() != 0) {

            //Verifica Se Tem Linha Selecionada
            if (jTableP.getSelectedRow() != -1) {
                Produto produtoSelecionado = repositorioProduto.getProduto(jTableP.getSelectedRow());

                int opcao = JOptionPane.showConfirmDialog(this, produtoSelecionado, "Quer Apagar O Produto ?", JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.YES_OPTION) {
                    repositorioProduto.RemoveProduto(jTableP.getSelectedRow());
                    JOptionPane.showMessageDialog(this, "Produto Removido Com Sucesso");
                } else {
                    JOptionPane.showMessageDialog(this, "Remoção Abortada");
                    jTableP.clearSelection();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Nenhum Produto Selecionado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não Possui Produtos Cadastrados");
        }
    }//GEN-LAST:event_jBRemovePActionPerformed

    private void jBEditaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditaPActionPerformed
        // Botão Para Editar

        if (jTableP.getRowCount() != 0) {

            //Verifica Se Tem Linha Selecionada
            if (jTableP.getSelectedRow() != -1) {

                Produto produtoSelecionado = repositorioProduto.getProduto(jTableP.getSelectedRow());
                int opcao = JOptionPane.showConfirmDialog(this, produtoSelecionado, "Quer Editar O Produto ?", JOptionPane.YES_NO_OPTION);
                if (opcao == JOptionPane.YES_OPTION) {

                    if (chamaTelaProduto == null) {
                        chamaTelaProduto = new TelaEditarProduto(produtoSelecionado);
                    }
                    chamaTelaProduto.setVisible(true);
                    repositorioProduto.AtualizaTablep();

                } else {
                    JOptionPane.showMessageDialog(this, "Edição Abortada");
                    jTableP.clearSelection();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum Produto Selecionado");

            }
        } else {
            JOptionPane.showMessageDialog(this, "Não Possui Produtos Cadastrados");
        }
    }//GEN-LAST:event_jBEditaPActionPerformed

    private void jBPesquisaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaPActionPerformed
        // Botão Para Pesquisar
        if (jTPesquisaP.getText().length() > 0) {
            //Pegando O Código e O Produto Pesquisado    
            Produto p = repositorioProduto.PesquisaProduto(Integer.parseInt(jTPesquisaP.getText()));

            if (p != null) {
                //Mostra O Produto Encontrado   
                JOptionPane.showMessageDialog(this, "Produto Encontrado" + "\n" + p);
                //Limpando Campo
                jTPesquisaP.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Não Possui Produtos Com Ese Código ");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Campo Em Branco");
        }

    }//GEN-LAST:event_jBPesquisaPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddP;
    private javax.swing.JButton jBEditaP;
    private javax.swing.JButton jBPesquisaP;
    private javax.swing.JButton jBRemoveP;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDescP;
    private javax.swing.JTextField jTNomeP;
    private javax.swing.JTextField jTPesquisaP;
    private javax.swing.JTextField jTPrecoCP;
    private javax.swing.JTextField jTPrecoVP;
    private javax.swing.JTable jTableP;
    // End of variables declaration//GEN-END:variables
}
